[FFI] catch exception in swig/ffi
Summary:
As Haiping's found out, setting LD_PRELOAD="libstdc++.so.6" allows hphp to
throw exceptions without segfaulting in swig. However, those exceptions still
need to be caught, otherwise python still core-dumps.

This diff adds exception handling in the invocation interface in swig, and
instead of returning a pointer to a constructed Variant, it returns NULL in case
of error. It also logs the error message and the injected stack trace from the
exception. Therefore, we can avoid crashing python, and also get a better idea
what goes wrong in the compiled php code.

Then in hpyp, the unwrap method needs to check whether the value v is NULL
before getting the type, and if so, throw some Python exception.

Test Plan:
made libcore-ffi

temporarily change hpyp to raise RuntimeError in unwrap:

import core
from facebook import hpyp
h = hpyp.Hpyp(core)
h.require_module('questions')

The following message was printed, without crashing python:
HipHop Notice:  Tried to invoke flib/questions/__init__.php but file not found.
Required file that does not exist: /flib/questions/__init__.php
    #0 at [flib/__flib.php:163]
    #1 require_module(), called at [:0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/users/qixin/hpyp/facebook/hpyp.py", line 560, in hphp_function
    return H.unwrap(result)
  File "/var/users/qixin/hpyp/facebook/hpyp.py", line 364, in unwrap
    raise RuntimeError('Failed calling into HPHP')
RuntimeError: Failed calling into HPHP

DiffCamp Revision: 125700
Reviewed By: hzhao
CC: hphp-diffs@lists, hsurreal, hzhao, viyer
Revert Plan:
OK